import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const karla = localFont({
  src: [
    {
      path: "../../public/fonts/static/Karla-Regular.ttf",
      weight: "100 900",
      style: "normal"
    },
    {
      path: "../../public/fonts/static/Karla-Bold.ttf",
      weight: "100 900",
      style: "bold"
    }
  ],
  variable: "--karla"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
